services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: utilities-nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${NORD_TOKEN}
      - CONNECT=Mexico
      - TECHNOLOGY=NordLynx
    restart: always

  server:
    image: depremu/utilities-server:latest
    container_name: utilities-server
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: utilities-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: utilities-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/ssl/domain
    depends_on:
      - server

volumes:
  postgres_data: