import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "../../components/context/LayoutContext";

export const useStylesForgotPassword = () => {
  const { isWeb, isTablet, isLargeTablet } = useResponsiveLayout();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F9F9F9",
      paddingHorizontal: 20,
    },
    containerSafeAreaView:{},
    imageUser: {
      width: 120,
      height: 120,
      marginBottom: 20,
    },
    contentContainer: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    title: {
      fontSize: 28,
      fontWeight: "bold",
      fontFamily: "fontApp",
      color: "#333",
      textAlign: "center",
      marginBottom: 20,
      textShadowColor: "#aaa",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    containerForm: {
      width: "100%",
      padding: 20,
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 5,
      maxWidth: isWeb || isTablet || isLargeTablet ? 500 : "100%",
      minWidth: isWeb || isTablet || isLargeTablet ? 300 : "auto",
    },
    user: {
      marginBottom: 15,
    },
    textUser: {
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "fontApp",
      color: "#555",
      marginBottom: 5,
    },
    textInputUser: {
      height: 45,
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#FAFAFA",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      fontFamily: "fontApp",

      shadowRadius: 2,
      elevation: 2,
    },
    date: {
      marginBottom: 15,
    },
    textDate: {
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "fontApp",
      color: "#555",
      marginBottom: 5,
    },
    textInputPass: {
      height: 45,
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#FAFAFA",
      fontFamily: "fontApp",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
      flex: 1,
    },
    buttonDatePicker: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
      marginBottom: 20,
      padding: 15,
      borderRadius: 8,
      backgroundColor: "#6F42C1",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    textDatePicker: {
      fontSize: 16,
      textAlign: "center",
      fontFamily: "fontApp",
      color: "#FFF",
    },
    newAccountView: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
    },
    newAccountText: {
      fontSize: 16,
      color: "#555",
      marginRight: 5,
      fontFamily: "fontApp",
    },
    textSignin: {
      fontSize: 14,
      color: "#007BFF",
      fontWeight: "bold",
      textDecorationLine: "underline",
      fontFamily: "fontApp",
    },
    imageShowPassword: {
      width: 30,
      height: 30,
    },
    videoShowPassword: {
      width: 40,
      height: 40,
      right: -5,
    },
    buttonShowPassword: {
      position: "absolute",
      right: 10,
      top: 0,
      bottom: 0,
      justifyContent: "center",
      padding: 10,
      zIndex: 3000,
    },
    main: {
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    buttonLogIn: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      borderRadius: 8,
      backgroundColor: "#FFF",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      marginVertical: 10,
    },
    buttonVerifyData: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      borderRadius: 8,
      backgroundColor: "green",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginVertical: 10,
    },
    textLogin: {
      fontSize: 16,
      fontWeight: "bold",
      color: "black",
      marginRight: 5,
      fontFamily: "fontApp",
    },
    textVerifyData: {
      fontSize: 16,
      fontWeight: "bold",
      color: "white",
      marginRight: 5,
      fontFamily: "fontApp",
    },
  });
};
