import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    flex: 1,
    alignItems: "center",
  },
  textTitle: {
    fontSize: 24,
    fontWeight: "bold",
    maxHeight: 30,
    marginBottom: 20,
    color: "#333",
    textAlign: "center",
  },
  formContainer: {
    width: "100%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: 20,
  },
  checkBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
    marginLeft: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: 200,
  },
  checkBox: {
    marginHorizontal: 5,
  },
  checkBoxText: {
    fontSize: 18,
    color: "#333",
    fontWeight: "500",
  },
  buttonSubmit: {
    backgroundColor: "#007BFF",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginBottom: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonLoadCamiones: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    margin: 10,
    maxWidth: 400,
    alignItems: "center",
    justifyContent: "center",
  },
  textsButtons: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
  },
  scrollView: {
    flex: 1,
    width: "100%",
    marginVertical: 10,
  },
  scrollViewContent: {
    flex: 1,
    width: "100%",
    flexWrap: "wrap",
    flexDirection: "row",
  },
  camiones: {
    marginTop: 20,
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
  },
  camion: {
    backgroundColor: "#fff",
    padding: 15,
    width: 200,
    height: 100,
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  camionText: {
    fontSize: 16,
    color: "#333",
  },
  camionDate: {
    fontSize: 14,
    color: "#777",
  },
  bussesButtons: {
    flex: 1,
    marginVertical: 5,
    flexDirection: "row",
    justifyContent: "space-around",
    maxHeight: 100,
  },
  buttonsShow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  textInput: {
    backgroundColor: "#f5f5f5",
    padding: 10,
    borderRadius: 5,
    marginBottom: 15,
    width: "100%",
  },
});

export { styles };
