import { useMemo } from "react";
import { useTheme } from "@context/ThemeContext";
import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "@context/LayoutContext";

const useStylesRecorderScreen = () => {
  const { getCommonStyles, getResponsiveValue } = useResponsiveLayout();
  const { colors } = useTheme();

  const styles = useMemo(
    () =>
      StyleSheet.create({
        container: {
          ...getCommonStyles("mainContainer"),
        },
        containerScrollView: {
          flex: 1,
          width: "100%",
        },
        contentContainer: {
          padding: getResponsiveValue(16, 20, 24),
          gap: getResponsiveValue(16, 20, 24),
        },
        contentWidth: {
          width: "100%",
          maxWidth: 640,
          alignSelf: "center",
          gap: getResponsiveValue(16, 20, 24),
        },
        backgroundShapeOne: {
          position: "absolute",
          width: "75%",
          height: getResponsiveValue(140, 180, 200),
          borderRadius: getResponsiveValue(120, 150, 180),
          backgroundColor: colors.primary,
          opacity: 0.06,
          top: -getResponsiveValue(60, 70, 80),
          right: -getResponsiveValue(30, 40, 50),
          transform: [{ rotate: "10deg" }],
        },
        backgroundShapeTwo: {
          position: "absolute",
          width: "70%",
          height: getResponsiveValue(140, 180, 200),
          borderRadius: getResponsiveValue(110, 140, 170),
          backgroundColor: colors.accent,
          opacity: 0.08,
          bottom: -getResponsiveValue(70, 80, 90),
          left: -getResponsiveValue(30, 40, 50),
          transform: [{ rotate: "-6deg" }],
        },
        heroCard: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(16, 18, 20),
          padding: getResponsiveValue(18, 20, 24),
          gap: getResponsiveValue(12, 14, 16),
          borderWidth: 1,
          borderColor: colors.border,
          shadowColor: colors.shadow,
          shadowOpacity: 0.14,
          shadowRadius: 16,
          shadowOffset: { width: 0, height: 10 },
          elevation: 6,
        },
        heroHeader: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          gap: getResponsiveValue(10, 12, 14),
        },
        heroTimer: {
          fontSize: getResponsiveValue(36, 40, 44),
          fontWeight: "800",
          color: colors.text,
          letterSpacing: 0.5,
          fontFamily: "System",
          fontVariant: ["tabular-nums"],
        },
        heroCaption: {
          fontSize: getResponsiveValue(14, 16, 18),
          color: colors.text,
          opacity: 0.85,
          fontFamily: "System",
        },
        headline: {
          width: "100%",
          gap: getResponsiveValue(6, 8, 10),
          alignSelf: "center",
        },
        title: {
          fontSize: getResponsiveValue(24, 26, 28),
          fontWeight: "800",
          color: colors.text,
          fontFamily: "System",
        },
        subtitle: {
          fontSize: getResponsiveValue(13, 14, 16),
          color: colors.text,
          opacity: 0.82,
          fontFamily: "System",
        },
        slider: {
          width: "100%",
          height: getResponsiveValue(44, 48, 52),
          marginTop: getResponsiveValue(10, 12, 14),
        },
        containerSlider: {
          width: "100%",
          alignItems: "center",
          gap: getResponsiveValue(8, 10, 12),
          paddingVertical: getResponsiveValue(8, 10, 12),
        },
        timeText: {
          fontSize: getResponsiveValue(12, 14, 16),
          color: colors.text,
          opacity: 0.8,
          fontFamily: "System",
        },
        card: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(14, 16, 18),
          padding: getResponsiveValue(16, 18, 20),
          gap: getResponsiveValue(10, 12, 14),
          borderWidth: 1,
          borderColor: colors.border,
          shadowColor: colors.shadow,
          shadowOpacity: 0.12,
          shadowRadius: 12,
          shadowOffset: { width: 0, height: 4 },
          elevation: 2,
        },
        listCard: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(14, 16, 18),
          padding: getResponsiveValue(14, 16, 18),
          borderWidth: 1,
          borderColor: colors.border,
          gap: getResponsiveValue(10, 12, 14),
          shadowColor: colors.shadow,
          shadowOpacity: 0.08,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 4 },
          elevation: 2,
        },
        primaryButton: {
          backgroundColor: colors.primary,
          borderRadius: getResponsiveValue(16, 18, 20),
          paddingVertical: getResponsiveValue(12, 14, 16),
        },
        primaryButtonText: {
          color: colors.background,
          fontWeight: "700",
          fontSize: getResponsiveValue(15, 16, 18),
        },
        cardHeader: {
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          width: "100%",
        },
        sectionTitle: {
          fontSize: getResponsiveValue(15, 17, 19),
          fontWeight: "600",
          color: colors.text,
          fontFamily: "System",
        },
        switch: {
          width: getResponsiveValue(48, 52, 56),
          height: getResponsiveValue(28, 30, 32),
        },
        input: {
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(10, 12, 14),
          fontSize: getResponsiveValue(14, 15, 16),
        },
        inputStretch: {
          flex: 1,
        },
        listItemInfo: {
          flex: 1,
          gap: getResponsiveValue(4, 6, 8),
        },
        listItemTitle: {
          fontSize: getResponsiveValue(14, 16, 18),
          fontWeight: "700",
          color: colors.text,
          fontFamily: "System",
        },
        listItemSubtitle: {
          fontSize: getResponsiveValue(12, 13, 14),
          color: colors.text,
          opacity: 0.8,
          fontFamily: "System",
        },
        mediaControls: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          width: "100%",
          gap: getResponsiveValue(12, 14, 16),
          paddingVertical: getResponsiveValue(8, 10, 12),
        },
        flatListContent: {
          gap: getResponsiveValue(10, 12, 14),
          paddingBottom: getResponsiveValue(32, 36, 40),
        },
        listActions: {
          flexDirection: "row",
          alignItems: "center",
          gap: getResponsiveValue(8, 10, 12),
        },
        listActionButton: {
          width: getResponsiveValue(44, 48, 52),
          height: getResponsiveValue(44, 48, 52),
          borderRadius: 999,
          margin: 0,
        },
        section: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(14, 16, 18),
          paddingVertical: getResponsiveValue(10, 12, 14),
          borderWidth: 1,
          borderColor: colors.border,
        },
        subheader: {
          color: colors.text,
          opacity: 0.82,
          fontSize: getResponsiveValue(13, 14, 15),
          fontWeight: "700",
          paddingHorizontal: getResponsiveValue(14, 16, 18),
        },
        listRow: {
          paddingHorizontal: getResponsiveValue(14, 16, 18),
          minHeight: getResponsiveValue(52, 56, 60),
        },
        listRowTitle: {
          color: colors.text,
          fontSize: getResponsiveValue(14, 15, 16),
          fontWeight: "600",
        },
        listRowDescription: {
          color: colors.text,
          opacity: 0.78,
          fontSize: getResponsiveValue(12, 13, 14),
        },
        inlineFieldRow: {
          flexDirection: "row",
          gap: getResponsiveValue(10, 12, 14),
          paddingHorizontal: getResponsiveValue(14, 16, 18),
          paddingBottom: getResponsiveValue(12, 14, 16),
          alignItems: "flex-end",
        },
        inlineChips: {
          flexDirection: "row",
          flexWrap: "wrap",
          gap: getResponsiveValue(8, 10, 12),
          paddingHorizontal: getResponsiveValue(14, 16, 18),
          paddingBottom: getResponsiveValue(12, 14, 16),
        },
        chipSmall: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderWidth: 1,
        },
        chipTextSmall: {
          color: colors.text,
          fontWeight: "600",
        },
        chipRow: {
          flexDirection: "row",
          flexWrap: "wrap",
          gap: getResponsiveValue(8, 10, 12),
        },
        statusChip: {
          backgroundColor: colors.accent,
          borderColor: colors.primary,
          borderWidth: 1,
        },
        statusChipText: {
          color: colors.text,
          fontWeight: "700",
        },
        waveformContainer: {
          width: "100%",
          height: getResponsiveValue(64, 70, 76),
          flexDirection: "row",
          alignItems: "flex-end",
          gap: getResponsiveValue(8, 9, 10),
        },
        waveformBar: {
          flex: 1,
          minWidth: 6,
          borderRadius: 12,
          backgroundColor: colors.primary,
          opacity: 0.85,
        },
        playerCard: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(14, 16, 18),
          padding: getResponsiveValue(14, 16, 18),
          gap: getResponsiveValue(12, 14, 16),
          borderWidth: 1,
          borderColor: colors.border,
          shadowColor: colors.shadow,
          shadowOpacity: 0.08,
          shadowRadius: 10,
          shadowOffset: { width: 0, height: 6 },
          elevation: 3,
        },
        playerMeta: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          gap: getResponsiveValue(10, 12, 14),
        },
        emptyState: {
          alignItems: "center",
          justifyContent: "center",
          paddingVertical: getResponsiveValue(28, 32, 36),
          gap: getResponsiveValue(10, 12, 14),
        },
        emptyTitle: {
          color: colors.text,
          fontSize: getResponsiveValue(16, 18, 20),
          fontWeight: "700",
        },
        emptySubtitle: {
          color: colors.text,
          opacity: 0.78,
          fontSize: getResponsiveValue(13, 14, 15),
        },
        infoRow: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          gap: getResponsiveValue(12, 14, 16),
          width: "100%",
          flexWrap: "wrap",
        },
        infoItem: {
          flexGrow: 1,
          minWidth: 120,
          backgroundColor: colors.background,
          borderRadius: getResponsiveValue(12, 14, 16),
          padding: getResponsiveValue(10, 12, 14),
          borderWidth: 1,
          borderColor: colors.border,
          gap: getResponsiveValue(4, 6, 8),
        },
        infoLabel: {
          fontSize: getResponsiveValue(12, 13, 14),
          color: colors.text,
          opacity: 0.72,
        },
        infoValue: {
          fontSize: getResponsiveValue(14, 16, 18),
          fontWeight: "700",
          color: colors.text,
        },
        heroPill: {
          backgroundColor: colors.primary,
          paddingHorizontal: getResponsiveValue(10, 12, 14),
          paddingVertical: getResponsiveValue(6, 7, 8),
          borderRadius: 999,
        },
        heroPillText: {
          color: colors.background,
          fontWeight: "700",
          fontSize: getResponsiveValue(12, 13, 14),
          letterSpacing: 0.3,
        },
        actionsRow: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "center",
          gap: getResponsiveValue(12, 14, 16),
          width: "100%",
          marginTop: getResponsiveValue(4, 6, 8),
        },
        outlinedButton: {
          flex: 1,
          borderRadius: getResponsiveValue(14, 16, 18),
        },
        outlinedButtonContent: {
          paddingVertical: getResponsiveValue(10, 12, 14),
        },
        fab: {
          borderRadius: 999,
        },
        metaRow: {
          flexDirection: "row",
          alignItems: "center",
          gap: getResponsiveValue(8, 10, 12),
        },
        metaPill: {
          paddingHorizontal: getResponsiveValue(8, 10, 12),
          paddingVertical: getResponsiveValue(4, 5, 6),
          borderRadius: 999,
          backgroundColor: colors.accent,
        },
        metaText: {
          color: colors.text,
          fontSize: getResponsiveValue(12, 13, 14),
          opacity: 0.85,
        },
        emptyIllustration: {
          width: getResponsiveValue(120, 140, 160),
          height: getResponsiveValue(80, 90, 100),
        },
        sectionCard: {
          width: "100%",
          backgroundColor: colors.secondary,
          borderRadius: getResponsiveValue(14, 16, 18),
          padding: getResponsiveValue(14, 16, 18),
          borderWidth: 1,
          borderColor: colors.border,
          gap: getResponsiveValue(6, 8, 10),
        },
        sectionHeader: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
          marginBottom: getResponsiveValue(4, 6, 8),
        },
        menuAnchor: {
          borderRadius: getResponsiveValue(12, 14, 16),
        },
        stepper: {
          alignItems: "center",
          flexDirection: "row",
          gap: getResponsiveValue(10, 12, 14),
          justifyContent: "space-between",
          width: "100%",
        },
        stepperValue: {
          paddingHorizontal: getResponsiveValue(16, 18, 20),
          paddingVertical: getResponsiveValue(10, 12, 14),
          borderRadius: getResponsiveValue(12, 14, 16),
          borderWidth: 1,
          borderColor: colors.border,
          minWidth: getResponsiveValue(76, 84, 92),
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: colors.background,
        },
        stepperValueText: {
          fontSize: getResponsiveValue(16, 18, 20),
          color: colors.text,
          fontWeight: "700",
        },
      }),
    [getCommonStyles, getResponsiveValue, colors],
  );

  return { styles };
};

export default useStylesRecorderScreen;
