FROM reactnativecommunity/react-native-android:latest

WORKDIR /utilities

RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get install -y nodejs \
    && node --version \
    && npm --version

RUN npm install -g eas-cli

COPY package.json yarn.lock ./
COPY common/package.json ./common/package.json
COPY app/package.json ./app/package.json

RUN yarn install --immutable

COPY . .

WORKDIR /utilities/app

CMD eas build \
  --platform android \
  --profile ${BUILD_PROFILE:-production} \
  --local \
  --output=/utilities/app/builds/android-${BUILD_PROFILE:-production}.apk
