export type Env<B extends boolean = false> = {
  API_URL: string;
  DB_USER: string;
  DB_PASS: string;
  JWT_SECRET: string;
  ADMIN_EMAIL: string;
  BUILD_PROFILE: "production" | "development" | string;
  DEEPL_TRANSLATOR_API: string;
  SECRET_KEY_TO_ENCRYPTION: string;
  FIREBASE_SERVICE_ACCOUNT: string;
  DB_ENCRYPTION_PASS: string;
  ADMIN_PASSWORD: string;
  USE_HTTPS: B extends true ? boolean : string;
  DB_NAME: string;
  DB_HOST: string;
  DB_PORT: B extends true ? number : string;
  __DEV__: B extends true ? boolean : string;
  WS_URL: string;
  IV: string;
};
