export type ScreensAvailable =
  | "Home"
  | "Test"
  | "Login"
  | "Games"
  | "InfoIP"
  | "SignUp"
  | "Cryptos"
  | "Settings"
  | "Clipboard"
  | "Calculator"
  | "Translator"
  | "SocialMedia"
  | "Minesweeper"
  | "forgotPassword"
  | "MarkdownViewer"
  | "DeviceInformation";
