import { typeLanguages } from "@types";

const en: typeLanguages = {
  success: "Success",
  welcomeUser: "Welcome back, {{user}}",
  close: "Close",
  dearUser: "Dear user",
  infoIP: "IP Information",
  cryptoInfo: "Cryptocurrency Information",
  user: "User",
  yourIP: "Your IP is: {{ip}}",
  location: "Location",
  organization: "Organization",
  asn: "ASN",
  isp: "ISP",
  city: "City",
  state: "State",
  country: "Country",
  countryCode: "Country Code",
  zipcode: "Zipcode",
  latitude: "Latitude",
  longitude: "Longitude",
  timezone: "Timezone",
  localTime: "Local Time",
  isMobile: "Is Mobile?",
  isVPN: "Is VPN?",
  isTOR: "Is TOR?",
  isProxy: "Is Proxy?",
  isDatacenter: "Is Datacenter?",
  riskScore: "Risk Score",
  currency: "Currency",
  continent: "Continent",
  continentCode: "Continent Code",
  region: "Region",
  regionName: "Region Name",
  as: "AS",
  asname: "AS Name",
  reverse: "Reverse",
  district: "District",
  asName: "AS Name",
  reverseDNS: "Reverse DNS",
  utcOffset: "UTC Offset",
  yes: "Yes",
  no: "No",
  notAvailable: "Not Available",
  isHosting: "Is Hosting?",
  status: "Status",
  selectCurrency: "Select Currency",
  priceOfCrypto: "The price of {{cryptoName}} is: ",
  clearCache: "Clear Cache",
  showSelected: "Show Selected",
  searchCrypto: "Search Cryptocurrency",
  ownedAmount: "You own: {{amount}} {{cryptoName}}",
  firstInvest:
    "You invested: {{amount}} {{cryptoName}} with the price of {{price}}",
  gainAmount: "You gained: {{gainAmount}} {{currency}}",
  noCryptosFound: "No cryptocurrencies found",
  showAll: "Show All",
  goToSelectionTab:
    "No cryptocurrencies selected. Go to the selection tab to choose the cryptocurrencies you want to track and monitor their performance.",
  myCryptoPortfolio: "My Cryptocurrency Portfolio",
  noCryptocurrenciesSelected: "No cryptocurrencies selected",
  autoRefresh: "Auto Refresh",
  cryptocurrenciesTracked: "Cryptocurrencies Tracked",
  // Login Screen translations
  errorNoSession: "Session Error",
  errorNoSessionMessage: "Could not create session. Please try again.",
  successSignUp: "Sign Up Successful",
  successSignUpMessage: "Your account has been created successfully.",
  verifyEmail: "Please verify your email to complete registration.",
  welcome: "Welcome",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  loginButton: "Login",
  rememberMe: "Remember Me",
  forgotPassword: "Forgot Password?",
  createAccount: "Create Account",
  hasAccount: "Already have an account?",
  signUp: "Sign Up",
  // Auth success messages
  successLogin: "Login Successful",
  successLoginMessage: "You have logged in successfully. Welcome!",
  NoInternetConnection: "No Internet Connection",
  PleaseCheckInternetConnection: "Please check your internet connection.",
  // Settings Screen translations
  settings: "Settings",
  adminSection: "Admin Section",
  passwordAdminSection: "Admin Password",
  checkPassword: "Check Password",
  setWebSocketURL: "Set WebSocket URL",
  webSocketURL: "WebSocket URL",
  save: "Save",
  apiURL: "API URL",
  setApiURL: "Set API URL",
  exitApp: "Exit App",
  back: "Back",
  backMessage: "Do you want to go back to the home screen?",
  exitAppMessage: "Are you sure you want to exit the app?",
  datePurchased: "Date purchased: {{date}}",
  language: "Language",
  setLanguage: "Select Language",
  logout: "Logout",
  notifications: "Notifications",
  setNotifications: "Set Notifications",
  cryptos: "Cryptocurrencies",
  notificationInterval: "Notification Interval",
  allNotifications: "All Notifications",
  appTheme: "App Theme",
  auto: "Auto",
  light: "Light",
  dark: "Dark",
  setTheme: "Select Theme",
  calculate: "Calculate",
  syntaxError: "Syntax Error",
  finances: "Finances",
  calculator: "Calculator",
  currentPrice: "Current Price",
  games: "Games",
  minesweeper: "Minesweeper",
  startGame: "Start Game",
  easy: "Easy",
  medium: "Medium",
  hard: "Hard",
  flagsRemaining: "Flags Remaining: {{count}}",
  youWin: "You Win!",
  youLose: "You Lose!",
  youArePlaying: "You Are Playing",
  undo: "Undo",
  successForgotPasswordMessage:
    "A password reset email has been sent. If you don't see it, check your spam folder.",
  sending: "Sending...",
  clipboard: "Clipboard",
  clipboardTitle: "Content",
  remove: "Remove",
  copy: "Copy",
  languageTarget: "Target Language",
  enterText: "Enter Text",
  translate: "Translate",
  translation: "Translation",
  translator: "Translator",
  English: "English",
  Spanish: "Spanish",
  French: "French",
  German: "German",
  Italian: "Italian",
  Japanese: "Japanese",
  Chinese: "Chinese",
  streamers: "Streamers",
  youAreNotLoggedIn: "You are not logged in",
  error: "Error",
  errorLoadingStreamers: "Error loading streamers.",
  streamerAlreadyAdded: "Streamer {{name}} is already added",
  askAddStreamerTitle: "Add Streamer",
  askAddStreamerBody: "Do you want to add the streamer {{name}}?",
  askDeleteStreamer: "Delete Streamer",
  askDeleteStreamerBody:
    "Are you sure you want to delete the streamer {{name}}?",
  delete: "Delete",
  errorDeletingStreamer: "Error deleting streamer: {{error}}",
  addStreamer: "Add Streamer",
  yourStreamers: "Your Streamers",
  askOpenURL: "Are you sure you want to open the URL {{url}}?",
  openURL: "Open URL",
  Live: "Live",
  Offline: "Offline",
  socialMedia: "Social Media",
  deviceInformation: "Device Information",
  appVersion: "App Version",
  systemName: "System Name",
  batteryLevel: "Battery Level",
  isCharging: "Is Charging?",
  totalMemory: "Total Memory",
  usedMemory: "Used Memory",
  totalStorage: "Total Storage",
  freeStorage: "Free Storage",
  carrier: "Carrier",
  ipAddress: "IP Address",
  macAddress: "MAC Address",
  isEmulator: "Is Emulator?",
  userAgent: "User Agent",
  brand: "Brand",
  model: "Model",
  systemVersion: "System Version",
  buildNumber: "Build Number",
  bundleId: "Bundle ID",
  deviceId: "Device ID",
  deviceName: "Device Name",
  isTablet: "Is Tablet?",
  hasNotch: "Has Notch?",
  charging: "Charging",
  full: "Full",
  unknown: "Unknown",
  hardware: "Hardware",
  hostname: "Hostname",
  host: "Host",
  startupTime: "Startup Time",
  uniqueId: "Unique ID",
  manufacturer: "Manufacturer",
  powerState: "Power State",
  unplugged: "Unplugged",
  batteryState: "Battery State",
  lowPowerMode: "Low Power Mode",
  BatteryLow: "Battery Low",
  YourBatteryIsLow: "Your Battery Is Low",
  BatteryFullyCharged: "Battery Fully Charged",
  YouCanUnplugYourDevice: "You Can Unplug Your Device",
  noClipboardData: "No clipboard items available",
  clipboardEmptyDescription:
    "Your clipboard is currently empty. Any text you copy on your device will appear here for easy access.",
  sync: "Sync",
  addToDatabase: "Add to Database",
  adding: "Adding...",
  addTextToClipboard: "Add Text to Clipboard",
  enterYourTextHere: "Enter your text here",
  errorOccurred: "An error occurred: {{error}}",
  failedToAddTextToDatabase: "Failed to add text to database",
  textAddedToDatabase: "Text added to database",
} as const;

export default en;
