import { typeLanguages } from "@types";

const en: typeLanguages = {
  success: "Success",
  welcomeUser: "Welcome, {{user}}",
  close: "Close",
  dearUser: "Dear user",
  infoIP: "IP Information",
  cryptoInfo: "Cryptocurrency Information",
  user: "User",
  yourIP: "Your IP is: {{ip}}",
  location: "Location",
  organization: "Organization",
  asn: "ASN",
  isp: "ISP",
  city: "City",
  state: "State",
  country: "Country",
  countryCode: "Country Code",
  zipcode: "Zipcode",
  latitude: "Latitude",
  longitude: "Longitude",
  timezone: "Timezone",
  localTime: "Local Time",
  isMobile: "Is Mobile?",
  isVPN: "Is VPN?",
  isTOR: "Is TOR?",
  isProxy: "Is Proxy?",
  isDatacenter: "Is Datacenter?",
  riskScore: "Risk Score",
  currency: "Currency",
  continent: "Continent",
  continentCode: "Continent Code",
  region: "Region",
  regionName: "Region Name",
  as: "AS",
  asname: "AS Name",
  reverse: "Reverse",
  district: "District",
  asName: "AS Name",
  reverseDNS: "Reverse DNS",
  utcOffset: "UTC Offset",
  yes: "Yes",
  no: "No",
  notAvailable: "Not Available",
  isHosting: "Is Hosting?",
  status: "Status",
  selectCurrency: "Select Currency",
  priceOfCrypto: "The price of {{cryptoName}} is: ",
  clearCache: "Clear Cache",
  showSelected: "Show Selected",
  searchCrypto: "Search Cryptocurrency",
  ownedAmount: "You own: {{amount}} {{cryptoName}}",
  firstInvest:
    "You invested: {{amount}} {{cryptoName}} with the price of {{price}}",
  gainAmount: "You gained: {{gainAmount}} {{currency}}",
  noCryptosFound: "No cryptocurrencies found",
  showAll: "Show All",
  goToSelectionTab:
    "No cryptocurrencies selected. Go to the selection tab to choose the cryptocurrencies you want to track and monitor their performance.",
  myCryptoPortfolio: "My Cryptocurrency Portfolio",
  noCryptocurrenciesSelected: "No cryptocurrencies selected",
  autoRefresh: "Auto Refresh",
  cryptocurrenciesTracked: "Cryptocurrencies Tracked",
  // Login Screen translations
  errorNoSession: "Session Error",
  errorNoSessionMessage: "Could not create session. Please try again.",
  successSignUp: "Sign Up Successful",
  successSignUpMessage: "Your account has been created successfully.",
  verifyEmail: "Please verify your email to complete registration.",
  welcome: "Welcome",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  loginButton: "Login",
  rememberMe: "Remember Me",
  forgotPassword: "Forgot Password?",
  createAccount: "Create Account",
  hasAccount: "Already have an account?",
  signUp: "Sign Up",
  // Auth success messages
  successLogin: "Login Successful",
  successLoginMessage: "You have logged in successfully. Welcome!",
  NoInternetConnection: "No Internet Connection",
  PleaseCheckInternetConnection: "Please check your internet connection.",
  // Settings Screen translations
  settings: "Settings",
  adminSection: "Admin Section",
  passwordAdminSection: "Admin Password",
  checkPassword: "Check Password",
  setWebSocketURL: "Set WebSocket URL",
  webSocketURL: "WebSocket URL",
  save: "Save",
  apiURL: "API URL",
  setApiURL: "Set API URL",
  exitApp: "Exit App",
  back: "Back",
  backMessage: "Do you want to go back to the home screen?",
  exitAppMessage: "Are you sure you want to exit the app?",
  datePurchased: "Date purchased: {{date}}",
  language: "Language",
  setLanguage: "Select Language",
  logout: "Logout",
  notifications: "Notifications",
  setNotifications: "Set Notifications",
  cryptos: "Cryptocurrencies",
  notificationInterval: "Notification Interval",
  allNotifications: "All Notifications",
  appTheme: "App Theme",
  auto: "Auto",
  light: "Light",
  dark: "Dark",
  setTheme: "Select Theme",
  calculate: "Calculate",
  syntaxError: "Syntax Error",
  finances: "Finances",
  calculator: "Calculator",
} as const;

export default en;
