import { typeLanguages } from "@types";

const es: typeLanguages = {
  success: "Éxito",
  welcomeUser: "Bienvenido, {{user}}",
  close: "Cerrar",
  dearUser: "Estimado usuario",
  infoIP: "Información de IP",
  cryptoInfo: "Información de criptomonedas",
  user: "Usuario",
  yourIP: "Tu IP es: {{ip}}",
  location: "Ubicación",
  organization: "Organización",
  asn: "ASN",
  isp: "ISP",
  city: "Ciudad",
  state: "Estado",
  country: "País",
  countryCode: "Código de país",
  zipcode: "Código postal",
  latitude: "Latitud",
  longitude: "Longitud",
  timezone: "Zona horaria",
  localTime: "Hora local",
  isMobile: "¿Es móvil?",
  isVPN: "¿Es VPN?",
  isTOR: "¿Es TOR?",
  isProxy: "¿Es proxy?",
  isDatacenter: "¿Es centro de datos?",
  riskScore: "Puntuación de riesgo",
  currency: "Moneda",
  continent: "Continente",
  continentCode: "Código de continente",
  region: "Región",
  regionName: "Nombre de la región",
  as: "AS",
  asname: "Nombre de AS",
  reverse: "Reverse",
  district: "Distrito",
  asName: "Nombre de AS",
  reverseDNS: "Reverse DNS",
  utcOffset: "UTC Offset",
  yes: "Sí",
  no: "No",
  notAvailable: "No disponible",
  isHosting: "¿Es hosting?",
  status: "Estado",
  selectCurrency: "Seleccionar moneda",
  priceOfCrypto: "El precio de {{cryptoName}} es: ",
  clearCache: "Limpiar caché",
  showSelected: "Mostrar seleccionados",
  searchCrypto: "Buscar criptomoneda",
  ownedAmount: "Tienes: {{amount}} {{cryptoName}}",
  firstInvest:
    "Invertiste: {{amount}} {{cryptoName}} con el precio de {{price}}",
  gainAmount: "Ganaste: {{gainAmount}} {{currency}}",
  noCryptosFound: "No se encontraron criptomonedas",
  showAll: "Mostrar todo",
  goToSelectionTab:
    "No hay criptomonedas seleccionadas. Ve a la pestaña de selección para elegir las criptomonedas que deseas rastrear y monitorear su rendimiento.",
  myCryptoPortfolio: "Mi cartera de criptomonedas",
  autoRefresh: "Actualización automática",
  cryptocurrenciesTracked: "Criptomonedas rastreadas",
  noCryptocurrenciesSelected: "No hay criptomonedas seleccionadas",
  // Login Screen translations
  errorNoSession: "Error de sesión",
  errorNoSessionMessage:
    "No se pudo crear la sesión. Por favor, inténtalo de nuevo.",
  successSignUp: "Registro exitoso",
  successSignUpMessage: "Tu cuenta ha sido creada exitosamente.",
  verifyEmail:
    "Por favor, verifica tu correo electrónico para completar el registro.",
  welcome: "Bienvenido",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  loginButton: "Iniciar sesión",
  rememberMe: "Recordarme",
  forgotPassword: "¿Olvidaste tu contraseña?",
  createAccount: "Crear cuenta",
  // SignUp Screen translations
  signUp: "Registrarse",
  hasAccount: "¿Ya tienes cuenta?",
  // Auth success messages
  successLogin: "Inicio de sesión exitoso",
  successLoginMessage: "Has iniciado sesión correctamente. ¡Bienvenido!",
  NoInternetConnection: "Sin conexión a Internet",
  PleaseCheckInternetConnection: "Por favor, verifica tu conexión a Internet.",
  // Settings Screen translations
  settings: "Configuración",
  adminSection: "Sección de Administrador",
  passwordAdminSection: "Contraseña de Administrador",
  checkPassword: "Verificar Contraseña",
  setWebSocketURL: "Configurar URL del WebSocket",
  webSocketURL: "URL del WebSocket",
  save: "Guardar",
  apiURL: "URL de la API",
  setApiURL: "Configurar URL de la API",
  exitApp: "Salir de la aplicación",
  exitAppMessage: "¿Estás seguro de que deseas salir de la aplicación?",
  back: "Volver",
  backMessage: "¿Deseas volver a la pantalla de inicio?",
  datePurchased: "Fecha de compra: {{date}}",
  language: "Idioma",
  setLanguage: "Seleccionar idioma",
  logout: "Cerrar sesión",
  notifications: "Notificaciones",
  setNotifications: "Configurar Notificaciones",
  cryptos: "Criptomonedas",
  notificationInterval: "Intervalo de Notificación",
  allNotifications: "Todas las Notificaciones",
  appTheme: "Tema de la aplicación",
  auto: "Automático",
  light: "Claro",
  dark: "Oscuro",
  setTheme: "Seleccionar tema",
  calculate: "Calcular",
  syntaxError: "Error de sintaxis",
  finances: "Finanzas",
  calculator: "Calculadora",
} as const;

export default es;
