import { typeLanguages } from "@types";

const es: typeLanguages = {
  success: "Éxito",
  welcomeUser: "Bienvenido de nuevo, {{user}}",
  close: "Cerrar",
  dearUser: "Estimado usuario",
  infoIP: "Información de IP",
  cryptoInfo: "Información de criptomonedas",
  user: "Usuario",
  yourIP: "Tu IP es: {{ip}}",
  location: "Ubicación",
  organization: "Organización",
  asn: "ASN",
  isp: "ISP",
  city: "Ciudad",
  state: "Estado",
  country: "País",
  countryCode: "Código de país",
  zipcode: "Código postal",
  latitude: "Latitud",
  longitude: "Longitud",
  timezone: "Zona horaria",
  localTime: "Hora local",
  isMobile: "¿Es móvil?",
  isVPN: "¿Es VPN?",
  isTOR: "¿Es TOR?",
  isProxy: "¿Es proxy?",
  isDatacenter: "¿Es centro de datos?",
  riskScore: "Puntuación de riesgo",
  currency: "Moneda",
  continent: "Continente",
  continentCode: "Código de continente",
  region: "Región",
  regionName: "Nombre de la región",
  as: "AS",
  asname: "Nombre de AS",
  reverse: "Reverse",
  district: "Distrito",
  asName: "Nombre de AS",
  reverseDNS: "Reverse DNS",
  utcOffset: "UTC Offset",
  yes: "Sí",
  no: "No",
  notAvailable: "No disponible",
  isHosting: "¿Es hosting?",
  status: "Estado",
  selectCurrency: "Seleccionar moneda",
  priceOfCrypto: "El precio de {{cryptoName}} es: ",
  clearCache: "Limpiar caché",
  showSelected: "Mostrar seleccionados",
  searchCrypto: "Buscar criptomoneda",
  ownedAmount: "Tienes: {{amount}} {{cryptoName}}",
  firstInvest:
    "Invertiste: {{amount}} {{cryptoName}} con el precio de {{price}}",
  gainAmount: "Ganaste: {{gainAmount}} {{currency}}",
  noCryptosFound: "No se encontraron criptomonedas",
  showAll: "Mostrar todo",
  goToSelectionTab:
    "No hay criptomonedas seleccionadas. Ve a la pestaña de selección para elegir las criptomonedas que deseas rastrear y monitorear su rendimiento.",
  myCryptoPortfolio: "Mi cartera de criptomonedas",
  autoRefresh: "Actualización automática",
  cryptocurrenciesTracked: "Criptomonedas rastreadas",
  noCryptocurrenciesSelected: "No hay criptomonedas seleccionadas",
  // Login Screen translations
  errorNoSession: "Error de sesión",
  errorNoSessionMessage:
    "No se pudo crear la sesión. Por favor, inténtalo de nuevo.",
  successSignUp: "Registro exitoso",
  successSignUpMessage: "Tu cuenta ha sido creada exitosamente.",
  verifyEmail:
    "Por favor, verifica tu correo electrónico para completar el registro.",
  welcome: "Bienvenido",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  loginButton: "Iniciar sesión",
  rememberMe: "Recordarme",
  forgotPassword: "¿Olvidaste tu contraseña?",
  createAccount: "Crear cuenta",
  // SignUp Screen translations
  signUp: "Registrarse",
  hasAccount: "¿Ya tienes cuenta?",
  // Auth success messages
  successLogin: "Inicio de sesión exitoso",
  successLoginMessage: "Has iniciado sesión correctamente. ¡Bienvenido!",
  NoInternetConnection: "Sin conexión a Internet",
  PleaseCheckInternetConnection: "Por favor, verifica tu conexión a Internet.",
  // Settings Screen translations
  settings: "Configuración",
  adminSection: "Sección de Administrador",
  passwordAdminSection: "Contraseña de Administrador",
  checkPassword: "Verificar Contraseña",
  setWebSocketURL: "Configurar URL del WebSocket",
  webSocketURL: "URL del WebSocket",
  save: "Guardar",
  apiURL: "URL de la API",
  setApiURL: "Configurar URL de la API",
  exitApp: "Salir de la aplicación",
  exitAppMessage: "¿Estás seguro de que deseas salir de la aplicación?",
  back: "Volver",
  backMessage: "¿Deseas volver a la pantalla de inicio?",
  datePurchased: "Fecha de compra: {{date}}",
  language: "Idioma",
  setLanguage: "Seleccionar idioma",
  logout: "Cerrar sesión",
  notifications: "Notificaciones",
  setNotifications: "Configurar Notificaciones",
  cryptos: "Criptomonedas",
  notificationInterval: "Intervalo de Notificación",
  allNotifications: "Todas las Notificaciones",
  appTheme: "Tema de la aplicación",
  auto: "Automático",
  light: "Claro",
  dark: "Oscuro",
  setTheme: "Seleccionar tema",
  calculate: "Calcular",
  syntaxError: "Error de sintaxis",
  finances: "Finanzas",
  calculator: "Calculadora",
  currentPrice: "Precio actual",
  games: "Juegos",
  minesweeper: "Buscaminas",
  startGame: "Iniciar juego",
  easy: "Fácil",
  medium: "Medio",
  hard: "Difícil",
  flagsRemaining: "Banderas restantes: {{count}}",
  youWin: "¡Tú ganas!",
  youLose: "¡Tú pierdes!",
  youArePlaying: "Estás jugando",
  undo: "Deshacer",
  successForgotPasswordMessage:
    "Se ha enviado un correo electrónico para restablecer la contraseña. Si no lo ves, revisa tu carpeta de spam.",
  sending: "Enviando...",
  clipboard: "Portapapeles",
  clipboardTitle: "Contenido",
  remove: "Eliminar",
  copy: "Copiar",
  languageTarget: "Idioma de destino",
  enterText: "Ingresar texto",
  English: "Inglés",
  Spanish: "Español",
  French: "Francés",
  German: "Alemán",
  Italian: "Italiano",
  Japanese: "Japonés",
  Chinese: "Chino",
  translate: "Traducir",
  translation: "Traducción",
  translator: "Traductor",
  streamers: "Streamers",
  youAreNotLoggedIn: "No has iniciado sesión",
  error: "Error",
  errorLoadingStreamers: "Error al cargar los streamers.",
  streamerAlreadyAdded: "El streamer {{name}} ya está agregado",
  askAddStreamerTitle: "¿Agregar streamer?",
  askAddStreamerBody:
    "¿Estás seguro de que deseas agregar al streamer {{name}}?",
  askDeleteStreamer: "¿Eliminar streamer?",
  askDeleteStreamerBody:
    "¿Estás seguro de que deseas eliminar al streamer {{name}}?",
  delete: "Eliminar",
  errorDeletingStreamer: "Error al eliminar el streamer: {{error}}",
  addStreamer: "Agregar streamer",
  yourStreamers: "Tus streamers",
  askOpenURL: "¿Estás seguro de que deseas abrir la URL {{url}}?",
  openURL: "Abrir URL",
  Live: "En vivo",
  Offline: "Desconectado",
  socialMedia: "Redes sociales",
  deviceInformation: "Información del dispositivo",
  appVersion: "Versión de la aplicación",
  systemName: "Nombre del sistema",
  batteryLevel: "Nivel de batería",
  isCharging: "¿Está cargando?",
  totalMemory: "Memoria total",
  usedMemory: "Memoria usada",
  totalStorage: "Almacenamiento total",
  freeStorage: "Almacenamiento libre",
  carrier: "Operador",
  ipAddress: "Dirección IP",
  macAddress: "Dirección MAC",
  isEmulator: "¿Es emulador?",
  userAgent: "Agente de usuario",
  brand: "Marca",
  model: "Modelo",
  systemVersion: "Versión del sistema",
  buildNumber: "Número de compilación",
  bundleId: "ID del paquete",
  deviceId: "ID del dispositivo",
  deviceName: "Nombre del dispositivo",
  isTablet: "¿Es tableta?",
  hasNotch: "¿Tiene muesca?",
  charging: "Cargando",
  full: "Completo",
  unknown: "Desconocido",
  hardware: "Hardware",
  hostname: "Nombre del host",
  host: "Host",
  startupTime: "Tiempo de inicio",
  uniqueId: "ID único",
  manufacturer: "Fabricante",
  powerState: "Estado de energía",
  unplugged: "Desenchufado",
  batteryState: "Estado de la batería",
  lowPowerMode: "Modo de bajo consumo",
  BatteryLow: "Batería baja",
  YourBatteryIsLow: "Tu batería está baja",
  BatteryFullyCharged: "Batería completamente cargada",
  YouCanUnplugYourDevice: "Puedes desconectar tu dispositivo",
  noClipboardData: "No hay elementos en el portapapeles",
  clipboardEmptyDescription:
    "Tu portapapeles está vacío. Cualquier texto que copies en tu dispositivo aparecerá aquí para un acceso fácil.",
  sync: "Sincronizar",
  addToDatabase: "Agregar a la base de datos",
  adding: "Agregando...",
  addTextToClipboard: "Agregar texto al portapapeles",
  enterYourTextHere: "Ingresa tu texto aquí",
  errorOccurred: "Ocurrió un error: {{error}}",
  failedToAddTextToDatabase: "No se pudo agregar el texto a la base de datos",
  textAddedToDatabase: "Texto agregado a la base de datos",
  test: "Prueba",
  pleaseEnterSomeText: "Por favor, ingresa algún texto",
  clipboardWebSocketError:
    "Ocurrió un error de conexión con el servicio de portapapeles. Por favor, verifica tu conexión a Internet e intenta reconectar. Mientras estés desconectado, la sincronización del portapapeles no funcionará.",
  retry: "Reintentar",
  foregroundNotificationTitle: "Utilities Activo",
  foregroundNotificationMessage:
    "Utilities se está ejecutando en segundo plano.",
  locationEnabled: "Verificar si la ubicación está habilitada",
  LocationServicesEnabled: "Servicios de ubicación habilitados",
  LocationServicesEnabledMessage:
    "La aplicación detectó que los servicios de ubicación están habilitados.",
  pause: "Pausar",
  stop: "Detener",
  batteryAlerts: "Alertas de batería",
  noInternetConnection: "Sin conexión a Internet",
  dismiss: "Descartar",
  locationPermission: "Permiso de ubicación",
  locationPermissionMessage:
    "Esta aplicación requiere acceso a la ubicación para proporcionar notificaciones cuando los servicios de ubicación están activos. Por favor, habilita los permisos de ubicación en la configuración de tu dispositivo, solo si deseas recibir estas notificaciones. Debes permitir el acceso a la ubicación en todo momento para que esta función funcione correctamente.",
  cancel: "Cancelar",
  accept: "Aceptar",
  InternetConnectionRestored: "Conexión a Internet restaurada",
  YouAreBackOnline: "Has vuelto a estar en línea",
  overlayPermission: "Permiso de superposición",
  overlayPermissionMessage:
    "Para mejorar tu experiencia, la aplicación requiere permisos de superposición. Por favor, habilita este permiso en la configuración de tu dispositivo para permitir que la aplicación muestre contenido sobre otras aplicaciones, esto es importante para abrir la aplicación desde las notificaciones.",
  markdownViewer: "Visor de Markdown",
  markdownPlaceholder: "Ingresa tu texto en markdown aquí...",
  batteryOptimizationPermission: "Permiso de optimización de batería",
  batteryOptimizationPermissionMessage:
    "Para asegurar que la aplicación funcione correctamente en segundo plano, por favor desactiva la optimización de batería para esta aplicación en la configuración de tu dispositivo. Esto ayudará a mantener un rendimiento constante y evitará interrupciones mientras usas las funciones en segundo plano.",
  lastUpdateCheck: "Última verificación de actualización",
  checkForUpdates: "Buscar actualizaciones",
  updateAvailable: "Actualización disponible",
  updateAvailableMessage:
    "Hay una nueva actualización disponible. ¿Te gustaría actualizar ahora?",
  later: "Más tarde",
  updateNow: "Actualizar ahora",
  noUpdates: "No hay actualizaciones disponibles",
  downDetector: "Detector de caídas",
  addNewWebPage: "Agregar nueva página web",
  downDetectorTitle: "Detector de caídas",
  visitWebsite: "Visitar sitio web",
  downDetectorEmptyDescription:
    "No se encontraron sitios web monitorizados. Agrega una nueva página web para comenzar a monitorear su estado.",
  noDownDetectorData: "No hay datos del Detector de caídas disponibles",
  sendNotification: "Enviar notificación",
  placeholderNewWebPage: "Ingresa la URL de la página web a monitorizar",
  pleaseEnterWebPageURL: "Por favor, ingresa la URL de la página web",
  webPageMustStartWithHTTP:
    "La URL de la página web debe comenzar con http o https",
  webPageAddedSuccessfully: "Página web agregada exitosamente",
  computerControl: "Control de computadora",
  turnOffComputer: "Apagar computadora",
  restartComputer: "Reiniciar computadora",
  noDevices: "No se encontraron dispositivos en la red",
  searchingDevices: "Buscando dispositivos...",
  computerControlTitle: "Control de Computadora",
  scanning: "Escaneando",
  search: "Buscar",
  turnOffCommandSent: "Comando de apagado enviado",
  turnOffCommandFailed: "Error al enviar el comando de apagado",
  restartCommandSent: "Comando de reinicio enviado",
  restartCommandFailed: "Error al enviar el comando de reinicio",
  terminalCommands: "Comandos de Terminal",
  command: "Comando",
  enterCommand: "Ingresar comando",
  "executeOnStart-up": "Ejecutar al iniciar",
  "executeOnShut-down": "Ejecutar al apagar",
  addCommand: "Agregar comando",
  noCommandsAdded: "No se han agregado comandos",
  commandExecuted: "Comando ejecutado",
  commandSentSuccessfully: "Comando enviado exitosamente",
  commandFailed: "Error en el comando",
  commandExecutionFailed: "Error al ejecutar el comando",
  commandOutput: "Salida del comando",
  askExecuteCommand: "¿Ejecutar comando?",
  confirmExecuteCommand:
    "Antes de ejecutar el comando, se recomienda probarlo primero para asegurarse de que funcione como se espera. ¿Quieres ejecutar el comando ahora?",
  execute: "Ejecutar",
  noOutput: "Sin salida",
  executingCommand: "Ejecutando comando...",
  loggingIn: "Iniciando sesión...",
  currentVersion: "Versión actual: {{version}}",
  appUpdates: "Actualizaciones de la aplicación",
  appUpdatesExplanation:
    "Las actualizaciones se descargan automáticamente en segundo plano. Si estás en Windows, es posible que veas un aviso de instalación al abrir la aplicación.",
  openUpdatesWebPage: "Abrir página web de actualizaciones",
  ourUpdatesWebPage: "Nuestra página web de actualizaciones",
} as const;

export default es;
