import { useMemo } from "react";
import { useTheme } from "@context/ThemeContext";
import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "@context/LayoutContext";

const useStylesNotesScreen = () => {
  const { colors } = useTheme();
  const { getCommonStyles } = useResponsiveLayout();

  const styles = useMemo(
    () =>
      StyleSheet.create({
        container: {
          ...getCommonStyles("mainContainer"),
          alignItems: undefined,
          justifyContent: "flex-start",
          paddingHorizontal: 14,
          paddingTop: 12,
        },
        searchInput: {
          backgroundColor: colors.secondary,
          borderRadius: 12,
          marginBottom: 4,
          width: "100%",
        },
        headerArea: {
          gap: 8,
          marginBottom: 12,
        },
        notesHeaderTopRow: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
          marginBottom: 2,
        },
        notesScreenTitle: {
          color: colors.text,
          fontSize: 44,
          fontWeight: "300",
          letterSpacing: 0.2,
        },
        notesHeaderTopActions: {
          alignItems: "center",
          flexDirection: "row",
          gap: 10,
        },
        headerIconButton: {
          alignItems: "center",
          backgroundColor: colors.secondary,
          borderColor: colors.border,
          borderRadius: 16,
          borderWidth: 1,
          height: 34,
          justifyContent: "center",
          width: 34,
        },
        settingsRow: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
        },
        settingsText: {
          color: colors.text,
        },
        folderRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 10,
          paddingBottom: 6,
          paddingTop: 4,
        },
        folderChip: {
          backgroundColor: colors.secondary,
          borderColor: "transparent",
          borderRadius: 18,
          borderWidth: 1,
          paddingHorizontal: 14,
          paddingVertical: 8,
        },
        folderChipActive: {
          backgroundColor: colors.accent,
          borderColor: colors.border,
        },
        folderChipText: {
          color: colors.text,
          fontSize: 13,
          fontWeight: "600",
        },
        folderChipAdd: {
          alignItems: "center",
          borderColor: colors.border,
          backgroundColor: colors.secondary,
          borderRadius: 18,
          borderWidth: 1,
          height: 36,
          justifyContent: "center",
          width: 36,
        },
        lockHintContainer: {
          alignItems: "center",
          flexDirection: "row",
          gap: 8,
          justifyContent: "center",
          marginBottom: 8,
        },
        lockHintText: {
          color: colors.text,
          fontSize: 12,
        },
        listContent: {
          gap: 12,
          paddingBottom: 120,
        },
        notesGridRow: {
          justifyContent: "space-between",
          marginBottom: 12,
        },
        noteCard: {
          backgroundColor: colors.secondary,
          borderColor: colors.accent,
          borderRadius: 24,
          borderWidth: 1,
          minHeight: 182,
        },
        noteCardGrid: {
          width: "49%",
        },
        noteCardSelected: {
          borderColor: colors.primary,
          borderWidth: 2,
        },
        noteCardContent: {
          gap: 10,
          minHeight: 164,
          padding: 10,
        },
        noteItem: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 16,
          borderWidth: 1,
          gap: 6,
          paddingHorizontal: 14,
          paddingVertical: 12,
          ...getCommonStyles("shadow"),
        },
        noteItemSelected: {
          borderColor: colors.primary,
          borderWidth: 1.5,
        },
        noteHeader: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
        },
        noteTitle: {
          color: colors.text,
          flex: 1,
          fontSize: 17,
          fontWeight: "600",
          marginRight: 8,
        },
        notePreview: {
          color: colors.text,
          fontSize: 13,
          lineHeight: 22,
          opacity: 0.75,
        },
        noteFooter: {
          alignItems: "center",
          flexDirection: "row",
          marginTop: 2,
          position: "absolute",
          right: 10,
          bottom: -10,
        },
        noteDate: {
          color: colors.text,
          fontSize: 12,
          opacity: 0.55,
        },
        notePinBadge: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 8,
          borderWidth: 1,
          flexDirection: "row",
          gap: 4,
          paddingHorizontal: 6,
          paddingVertical: 2,
        },
        notePinBadgeText: {
          color: colors.text,
          fontSize: 11,
          opacity: 0.8,
        },
        emptyContainer: {
          alignItems: "center",
          justifyContent: "center",
          paddingVertical: 24,
        },
        emptyText: {
          color: colors.text,
          opacity: 0.8,
          textAlign: "center",
        },
        fab: {
          right: 20,
          bottom: 20,
          position: "absolute",
          borderWidth: 1,
          borderColor: colors.accent,
          backgroundColor: colors.primary,
        },
        bottomActions: {
          backgroundColor: colors.secondary,
          borderColor: colors.primary,
          borderRadius: 14,
          borderWidth: 1.5,
          bottom: 16,
          flexDirection: "row",
          justifyContent: "space-between",
          left: 12,
          padding: 10,
          position: "absolute",
          right: 12,
          ...getCommonStyles("shadow"),
        },
        actionButton: {
          alignItems: "center",
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          height: 34,
          justifyContent: "center",
          width: 34,
        },
        actionText: {
          color: colors.text,
          fontSize: 13,
          fontWeight: "600",
        },
        actionTextDanger: {
          color: colors.error,
          fontSize: 13,
          fontWeight: "600",
        },
        modalContainer: {
          backgroundColor: colors.background,
          borderRadius: 14,
          gap: 12,
          margin: 20,
          padding: 16,
          ...getCommonStyles("shadow"),
        },
        modalContainerLarge: {
          backgroundColor: colors.background,
          borderRadius: 14,
          margin: 20,
          maxHeight: "80%",
          padding: 16,
          ...getCommonStyles("shadow"),
        },
        modalTitle: {
          color: colors.text,
          fontSize: 18,
          fontWeight: "700",
        },
        modalSubtitle: {
          color: colors.text,
          opacity: 0.8,
        },
        modalPrimaryButton: {
          alignItems: "center",
          backgroundColor: colors.primary,
          borderRadius: 8,
          paddingVertical: 10,
        },
        modalPrimaryButtonText: {
          color: colors.background,
          fontWeight: "700",
        },
        hiddenNoteItem: {
          borderBottomColor: colors.border,
          borderBottomWidth: 1,
          paddingVertical: 10,
        },
        hiddenNoteTitle: {
          color: colors.text,
          fontWeight: "600",
        },
        hiddenNotePreview: {
          color: colors.text,
          opacity: 0.8,
        },
        hiddenModalFull: {
          ...getCommonStyles("mainContainer"),
          alignSelf: "center",
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 0,
          borderWidth: 1,
          height: "90%",
          paddingHorizontal: 12,
          paddingTop: 14,
          width: "100%",
        },
        hiddenList: {
          flex: 1,
          width: "100%",
        },
        hiddenListContent: {
          gap: 10,
          paddingBottom: 20,
        },
        moveFoldersScroll: {
          maxHeight: 320,
        },
        editorContainer: {
          backgroundColor: colors.background,
          borderRadius: 12,
          margin: 10,
          maxHeight: "95%",
          padding: 10,
          width: "100%",
        },
        editorWrapper: {
          gap: 8,
        },
        editorHeaderTop: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
        },
        editorHeaderActions: {
          alignItems: "center",
          flexDirection: "row",
          gap: 10,
        },
        editorMetaContainer: {
          gap: 4,
        },
        editorTitleInput: {
          backgroundColor: "transparent",
          fontSize: 22,
          fontWeight: "700",
          paddingHorizontal: 0,
          width: "100%",
        },
        editorMetaText: {
          color: colors.text,
          fontSize: 12,
          opacity: 0.7,
        },
        editorBody: {
          maxHeight: "65%",
        },
        editorBodyContent: {
          gap: 0,
        },
        editorContentInput: {
          minHeight: 180,
          flex: 1,
        },
        editorLinesContainer: {
          backgroundColor: colors.background,
          borderColor: colors.primary,
          borderRadius: 10,
          borderWidth: 1,
          gap: 0,
          minHeight: 180,
          paddingHorizontal: 6,
          paddingVertical: 4,
        },
        editorLineNativeInput: {
          backgroundColor: "transparent",
          minHeight: 0,
          paddingHorizontal: 0,
          paddingVertical: 0,
          margin: 0,
          includeFontPadding: false,
          textAlignVertical: "top",
        },
        textColorPickerModal: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 14,
          borderWidth: 1,
          marginHorizontal: 20,
          padding: 14,
        },
        textColorPicker: {
          width: "100%",
          alignSelf: "center",
          gap: 10,
          justifyContent: "center",
          marginBottom: 12,
        },
        textColorPickerHue: {
          justifyContent: "center",
          alignSelf: "center",
        },
        textColorPickerPanel: {
          width: "70%",
          height: "70%",
          alignSelf: "center",
          borderRadius: 10,
        },
        embeddedPreviewContainer: {
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          gap: 8,
          padding: 10,
        },
        embeddedText: {
          color: colors.text,
          fontSize: 15,
          lineHeight: 22,
        },
        embeddedDivider: {
          backgroundColor: colors.border,
          height: 1,
          marginVertical: 2,
          opacity: 0.5,
          width: "100%",
        },
        attachmentItem: {
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          overflow: "hidden",
        },
        attachmentImage: {
          height: 160,
          width: "100%",
        },
        attachmentFileRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 8,
          padding: 12,
        },
        attachmentFileName: {
          color: colors.text,
          flex: 1,
        },
        viewerAttachmentGrid: {
          flexDirection: "row",
          flexWrap: "wrap",
          gap: 10,
        },
        viewerAttachmentCard: {
          backgroundColor: colors.background,
          borderColor: colors.primary,
          borderRadius: 12,
          borderWidth: 1,
          minHeight: 104,
          overflow: "hidden",
          position: "relative",
          width: "48%",
        },
        viewerAttachmentContent: {
          flex: 1,
        },
        viewerAttachmentImage: {
          height: 120,
          width: "100%",
        },
        viewerAttachmentRemove: {
          alignItems: "center",
          backgroundColor: colors.secondary,
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          height: 22,
          justifyContent: "center",
          position: "absolute",
          right: 6,
          top: 6,
          width: 22,
        },
        viewerAttachmentFileRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 8,
          padding: 10,
        },
        viewerAttachmentFileName: {
          color: colors.text,
          flex: 1,
          fontSize: 12,
          lineHeight: 16,
        },
        previewCard: {
          backgroundColor: colors.background,
          borderColor: colors.primary,
          borderRadius: 12,
          borderWidth: 1,
          gap: 8,
          padding: 12,
        },
        previewTitle: {
          color: colors.text,
          fontSize: 16,
          fontWeight: "700",
        },
        previewContent: {
          color: colors.text,
          fontSize: 14,
          lineHeight: 20,
          opacity: 0.9,
        },
        previewInlineFlow: {
          alignItems: "center",
          flexDirection: "row",
          flexWrap: "wrap",
          gap: 6,
        },
        previewInlineText: {
          color: colors.text,
          fontSize: 14,
          lineHeight: 20,
          opacity: 0.9,
        },
        previewInlineBreak: {
          width: "100%",
        },
        previewInlineListItem: {
          alignItems: "center",
          flexDirection: "row",
          gap: 4,
          minHeight: 20,
        },
        previewInlineListText: {
          color: colors.text,
          fontSize: 14,
          lineHeight: 20,
          opacity: 0.9,
        },
        previewInlineAttachmentChip: {
          alignItems: "center",
          borderColor: colors.primary,
          borderRadius: 8,
          borderWidth: 1,
          flexDirection: "row",
          maxWidth: 200,
          minHeight: 34,
          overflow: "hidden",
          paddingHorizontal: 6,
          paddingVertical: 4,
        },
        previewInlineImage: {
          borderRadius: 6,
          height: 56,
          width: 56,
        },
        previewInlineFileRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 4,
          maxWidth: 180,
        },
        previewInlineFileText: {
          color: colors.text,
          fontSize: 12,
          maxWidth: 150,
        },
        previewInlineAudioChip: {
          alignItems: "center",
          borderColor: colors.primary,
          borderRadius: 8,
          borderWidth: 1,
          flexDirection: "row",
          gap: 2,
          minHeight: 34,
          paddingHorizontal: 4,
          paddingVertical: 2,
        },
        previewInlineAudioText: {
          color: colors.text,
          fontSize: 11,
          marginRight: 4,
        },
        editorToolbar: {
          maxHeight: 56,
        },
        editorToolbarRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 8,
          paddingVertical: 4,
        },
        toolbarButton: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          flexDirection: "row",
          gap: 6,
          paddingHorizontal: 10,
          paddingVertical: 8,
        },
        toolbarButtonText: {
          color: colors.text,
          fontSize: 12,
        },
        textCustomizeControlsRow: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          flexDirection: "row",
          gap: 4,
          marginTop: 4,
          paddingHorizontal: 6,
          paddingVertical: 4,
        },
        audioRecordControlsRow: {
          alignItems: "center",
          flexDirection: "row",
          gap: 8,
          marginTop: 4,
        },
        audioRecordTimer: {
          color: colors.text,
          fontSize: 13,
          marginLeft: 4,
          opacity: 0.9,
        },
        audioChoiceModal: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 14,
          borderWidth: 1,
          marginHorizontal: 20,
          padding: 14,
        },
        audioChoiceRow: {
          flexDirection: "row",
          gap: 10,
          justifyContent: "space-between",
        },
        audioChoiceButton: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 12,
          borderWidth: 1,
          flex: 1,
          gap: 8,
          paddingVertical: 14,
        },
        audioChoiceText: {
          color: colors.text,
          fontSize: 13,
          fontWeight: "600",
        },
        saveButton: {
          alignItems: "center",
          backgroundColor: colors.primary,
          borderRadius: 8,
          marginTop: 4,
          minHeight: 44,
          paddingVertical: 10,
          width: "100%",
        },
        saveButtonText: {
          color: colors.background,
          fontWeight: "700",
        },
        attachmentPreviewModal: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 0,
          borderWidth: 1,
          height: "100%",
          margin: 0,
          paddingHorizontal: 12,
          paddingVertical: 12,
          width: "100%",
        },
        attachmentPreviewWrapper: {
          flex: 1,
          gap: 10,
          width: "100%",
        },
        attachmentPreviewHeader: {
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "space-between",
        },
        attachmentPreviewTitle: {
          color: colors.text,
          flex: 1,
          fontSize: 14,
          fontWeight: "600",
          marginRight: 10,
        },
        attachmentPreviewImage: {
          flex: 1,
          minHeight: 280,
          width: "100%",
        },
        attachmentPreviewPdf: {
          flex: 1,
          minHeight: 280,
          width: "100%",
        },
        attachmentPreviewError: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 12,
          borderWidth: 1,
          gap: 12,
          justifyContent: "center",
          minHeight: 280,
          padding: 16,
        },
        attachmentPreviewErrorText: {
          color: colors.text,
          textAlign: "center",
        },
        attachmentPreviewFileContainer: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 12,
          borderWidth: 1,
          gap: 12,
          justifyContent: "center",
          marginTop: 20,
          padding: 16,
        },
        attachmentPreviewFileName: {
          color: colors.text,
          fontSize: 14,
          textAlign: "center",
        },
        attachmentPreviewAudioContainer: {
          alignItems: "center",
          borderColor: colors.border,
          borderRadius: 12,
          borderWidth: 1,
          gap: 12,
          justifyContent: "center",
          minHeight: 180,
          padding: 16,
        },
        attachmentPreviewAudioTime: {
          color: colors.text,
          fontSize: 13,
          opacity: 0.9,
        },
        viewerContainer: {
          ...getCommonStyles("mainContainer"),
          alignItems: undefined,
          justifyContent: "flex-start",
          gap: 10,
          paddingHorizontal: 12,
          paddingTop: 10,
        },
        emptyContainerViewer: {
          ...getCommonStyles("mainContainer"),
          alignItems: "center",
          gap: 12,
          justifyContent: "center",
          paddingHorizontal: 20,
        },
        settingsScreenContainer: {
          ...getCommonStyles("mainContainer"),
          alignItems: undefined,
          justifyContent: "flex-start",
          paddingHorizontal: 12,
          paddingTop: 12,
        },
        settingsCard: {
          backgroundColor: colors.background,
          borderColor: colors.border,
          borderRadius: 12,
          borderWidth: 1,
          gap: 12,
          padding: 12,
          ...getCommonStyles("shadow"),
        },
        settingsHintCard: {
          borderColor: colors.border,
          borderRadius: 10,
          borderWidth: 1,
          paddingHorizontal: 10,
          paddingVertical: 10,
        },
        settingsHintText: {
          color: colors.text,
          fontSize: 12,
          opacity: 0.75,
        },
      }),
    [getCommonStyles, colors],
  );

  return {
    styles,
    colors,
  };
};

export default useStylesNotesScreen;
